# Generated by Django 3.2.6 on 2022-11-29 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='category',
            fields=[
                ('id_category', models.AutoField(primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='genre',
            fields=[
                ('id_genre', models.AutoField(primary_key=True, serialize=False)),
                ('genre', models.CharField(max_length=100)),
            ],
        ),
    ]
