# Generated by Django 3.2.6 on 2022-10-21 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='genre',
            fields=[
                ('id_genre', models.AutoField(primary_key=True, serialize=False)),
                ('genre', models.CharField(max_length=100)),
            ],
        ),
    ]
