# Generated by Django 3.2.6 on 2022-11-03 10:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('playlist', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='recommendation',
            fields=[
                ('id_recommendation', models.AutoField(primary_key=True, serialize=False)),
                ('id_playlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='idplaylist', to='playlist.playlist')),
            ],
        ),
    ]
