# Generated by Django 3.2.6 on 2022-11-29 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('kdrama', '0001_initial'),
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='playlist',
            fields=[
                ('id_playlist', models.AutoField(primary_key=True, serialize=False)),
                ('id_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='idcategory', to='category.category')),
                ('id_genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='idgenre', to='category.genre')),
                ('id_kdrama', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='idkdrama', to='kdrama.kdrama')),
            ],
        ),
    ]
